// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace LigerShark.Farticus
{
    internal sealed partial class Vsix
    {
        public const string Id = "1324ce08-8b25-440c-8d5c-07e1fa0cce4a";
        public const string Name = "Farticus";
        public const string Description = @"The original Visual Studio fart app";
        public const string Language = "en-US";
        public const string Version = "2.0";
        public const string Author = "Sayed Hashimi & Mads Kristensen";
        public const string Tags = "fart, sound";
    }
}
